### ISSUE TITLE
setting page not displaying.

### ISSUE THREAD

**Issue by lahirubro123** [Nick-Hopps/v2-ui-plus#11]
![Capture](https://user-images.githubusercontent.com/72745298/135592010-8f1562e7-2194-4dc5-a065-ce637dc1d6ae.PNG)

http://167.99.71.232:65432/v2ray/setting/

**Comment by Nick-Hopps** [comment]
![IMG_0370](https://user-images.githubusercontent.com/16911282/135592430-7e9c71dd-9bef-4bc3-8bc5-92a3ee3072f8.png)

**Comment by Nick-Hopps** [comment]
Maybe it’s the problem of english translation.

**Comment by lahirubro123** [comment]
can fix it using editor ?

**Comment by lahirubro123** [comment]
or can i use chinees language I cannot change password because  this page not working

**Comment by Nick-Hopps** [comment]
you can use chinese for the moment, I have no idea where this error happens and I still need time to inspect.

**Comment by lahirubro123** [comment]
its ok how can i install chainees i clone repo and run it runs on english

**Comment by Nick-Hopps** [comment]
v2-ui using flask-babel for i18n, you can add config manually in init.py:

app.config["DEFAULT_BABEL_LOCALE"] = "zh"  # 设置默认语言
