### ISSUE TITLE
用Docker安装成功了，但是连接不上，跑不了

### ISSUE THREAD

**Issue by cshitian** [Nick-Hopps/v2-ui-plus#12]
添加了账号，然后现在使用没反应....
怎么排查问题？

**Comment by Nick-Hopps** [comment]
端口映射没问题吗？

**Comment by cshitian** [comment]
不清楚啊     ，用苹果的小火箭连接   显示超时

**Comment by cshitian** [comment]
centos 用的8.2的  我试试7看看

**Comment by Nick-Hopps** [comment]
emmm，具体的运行配置呢？你运行的docker命令，还有你面板的配置？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 用Docker安装成功了，但是连接不上，跑不了 (Issue #12)




 
不清楚啊     ，用苹果的小火箭连接   显示超时

**Comment by cshitian** [comment]
curl -sSL https://get.daocloud.io/docker | sh
sudo systemctl start docker
解压下载的包
进入文件夹
docker build --tag v2-ui .
docker run -d -p 65432:65432 v2-ui

**Comment by Nick-Hopps** [comment]
你这里只指定了 v2-ui 的端口，没开里面具体服务得端口啊，如果你用默认的1080，那还需要映射本地的1080端口。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 用Docker安装成功了，但是连接不上，跑不了 (Issue #12)




 
curl -sSL https://get.daocloud.io/docker | sh
 sudo systemctl start docker
 解压下载的包
 进入文件夹
 docker build --tag v2-ui .
 docker run -d -p 65432:65432 v2-ui

**Comment by cshitian** [comment]
......这个咋弄   没搞过

**Comment by Nick-Hopps** [comment]
就跟绑定65432一样，你运行的时候绑定你面板里面开的端口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 用Docker安装成功了，但是连接不上，跑不了 (Issue #12)




 
......这个咋弄   没搞过

**Comment by cshitian** [comment]
明白  好的 谢谢了

**Comment by cshitian** [comment]
docker run -d -p 1080:1080 v2-ui
还是不行

**Comment by Nick-Hopps** [comment]
你这样面板又不行了。。1080和65432都要



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 晚上6:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 用Docker安装成功了，但是连接不上，跑不了 (Issue #12)




 
docker run -d -p 1080:1080 v2-ui
 还是不行

**Comment by cshitian** [comment]
咳咳    纯小白
docker run -d -p 65432:65432 -p 1080:1080 v2-ui

**Comment by Nick-Hopps** [comment]
对滴



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 晚上6:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 用Docker安装成功了，但是连接不上，跑不了 (Issue #12)




 
咳咳    纯小白
 docker run -d -p 65432:65432 -p 1080:1080 v2-ui
