### ISSUE TITLE
docker run后容器直接exit了

### ISSUE THREAD

**Issue by RealSlakey** [Nick-Hopps/v2-ui-plus#13]
用的是 `docker run -d --network host v2-ui` 命令，随后用docker ps 无运行中容器显示，便用docker ps -a 查看刚开始运行就退出了
```
[root@C20220222213808 v2-ui]# docker run -d --network host v2-ui
73fbf3fbd0bc60b2da4654995962be59dd99831e082199d8dbd47827bd087d54
[root@C20220222213808 v2-ui]# docker ps -a
CONTAINER ID   IMAGE     COMMAND              CREATED         STATUS                     PORTS     NAMES
73fbf3fbd0bc   v2-ui     "python3 v2-ui.py"   6 seconds ago   Exited (1) 4 seconds ago             silly_hodgkin
```
系统是centos 7.8

**Comment by Nick-Hopps** [comment]
看下日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月17日(周四) 凌晨0:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Nick-Hopps/v2-ui-plus] docker run后容器直接exit了 (Issue #13)




 
用的是 docker run -d --network host v2-ui 命令，随后用docker ps 无运行中容器显示，便用docker ps -a 查看刚开始运行就退出了
 ***@***.*** v2-ui]# docker run -d --network host v2-ui 73fbf3fbd0bc60b2da4654995962be59dd99831e082199d8dbd47827bd087d54 ***@***.*** v2-ui]# docker ps -a CONTAINER ID   IMAGE     COMMAND              CREATED         STATUS                     PORTS     NAMES 73fbf3fbd0bc   v2-ui     "python3 v2-ui.py"   6 seconds ago   Exited (1) 4 seconds ago             silly_hodgkin  
系统是centos 7.8
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RealSlakey** [comment]
[root@C20220222213808 ~]# docker logs --details 73fbf3fbd0bc
 Traceback (most recent call last):
   File "v2-ui.py", line 10, in <module>
     from init import BASE_DIR, app
   File "/root/init.py", line 8, in <module>
     from flask import Flask, request, redirect, url_for, jsonify
   File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
     from . import json
   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)

**Comment by RealSlakey** [comment]
感谢提醒，看了日志将requirements中Flask版本改成2.0.2后能运行了

**Comment by Nick-Hopps** [comment]
OK
