### ISSUE TITLE
请问用啥命令安装...不太会

### ISSUE THREAD

**Issue by gcphym** [Nick-Hopps/v2-ui-plus#2]
请问用啥命令安装...不太会

**Comment by gcphym** [comment]
另外请问会支持用户自定义配置文件吗 原来那个项目修改配置文件 重启之后会被自动恢复 只能修改数据库...

**Comment by Nick-Hopps** [comment]
项目还在完善中，目前可以试用但不建议投入使用，等合并配置的功能写好后再用即可。

使用方法就是项目拉下去直接用 python 运行 `python v2-ui.py`，等全部功能写完后再考虑编译静态版本。

至于自定义配置文件，要么直接修改 template，要么添加新的配置就好，刚开始我加了自定义配置文件路径，发现使用体验实际上并不好，因此就固定使用原作者这种修改配置的方式了。

**Comment by gcphym** [comment]
> 项目还在完善中，目前可以试用但不建议投入使用，等合并配置的功能写好后再用即可。
> 
> 使用方法就是项目拉下去直接用 python 运行 `python v2-ui.py`，等全部功能写完后再考虑编译静态版本。
> 
> 至于自定义配置文件，要么直接修改 template，要么添加新的配置就好，刚开始我加了自定义配置文件路径，发现使用体验实际上并不好，因此就固定使用原作者这种修改配置的方式了。

谢谢
