### ISSUE TITLE
[BUG]当对某一用户创建超过1个以上配置文件时，此用户登录后用户信息会卡在加载中

### ISSUE THREAD

**Issue by cntzjjs** [Nick-Hopps/v2-ui-plus#8]
当对某一用户创建超过1个以上配置信息时，例如2个或者2个+。
此用户登录后账号列表会卡在加载中。
当删减为一个配置信息即恢复正常。

**Comment by Nick-Hopps** [comment]
这个是已知的问题，因为目前个人页面只写了VMESS的配置，其他类型的配置还没写，工作量有点大所以搁置了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日(周五) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Nick-Hopps/v2-ui-plus] [BUG]当对某一用户创建超过1个以上配置文件时，此用户登录后用户信息会卡在加载中 (#8)




 
当对某一用户创建超过1个以上配置信息时，例如2个或者2个+。
 此用户登录后用户信息会卡在加载中。
 当删减为一个配置文件即恢复正常。

**Comment by Nick-Hopps** [comment]
等春招后找时间完善。
